### ISSUE TITLE
有没有API

### ISSUE THREAD

**Issue by BetyChen** [AppscommOpenSource/AppscommBluetoothSDK-iOS#1]
有没有 API

**Comment by BetyChen** [comment]
连接手环的时候会卡死

**Comment by AppscommOpenSource** [comment]
1.所有的蓝牙操作都在后台dispatch里面，回调时要回到main 线程来。
2.如果用到的是L28S系列手环，需要调用连接设备方法之后，按下按钮点亮设备屏幕、开启蓝牙。
3.能不能详细说一下如何调用的方法，把关键代码贴上来？或者你先用Demo的程序连一下手环？
